builder:
  build: .
  dockerfile: Dockerfile-builder
  volumes:
   - $PWD:/build
   - $SSH_AUTH_SOCK:/ssh-agent
  environment:
    # make ssh keys available via ssh forwarding (see volume entry)
    - SSH_AUTH_SOCK=/ssh-agent
