builder:
  image: hub.noths.com/golang:v1.7
  volumes:
    - ${PWD}:/build
    - ${SSH_AUTH_SOCK}:/ssh-agent
  environment:
    - SSH_AUTH_SOCK=/ssh-agent
    - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin
    - GOPATH=/go
  command: |
    sh -c 'apk --update add git openssh-client \
    && git config --global url."git@github.com:".insteadOf "https://github.com/" \
    && mkdir ~/.ssh \
    && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config \
    && go get -d -v github.com/notonthehighstreet/consul-cleaner \
    && go install --ldflags "-X main.version=${GIT_TAG_NAME} -extldflags -static -s" -v github.com/notonthehighstreet/consul-cleaner \
    && mkdir /build/build \
    && cp -r /go/bin/* /build/build'
